COPY "@TABLEPREFIX@taxon" FROM '@BASEPATH@taxa.txt' WITH DELIMITER AS '	' CSV HEADER;
COPY "@TABLEPREFIX@distribution" FROM '@BASEPATH@distribution.txt' WITH DELIMITER AS '	' CSV HEADER;
COPY "@TABLEPREFIX@reference" FROM '@BASEPATH@reference.txt' WITH DELIMITER AS '	' CSV HEADER;
COPY "@TABLEPREFIX@vernacular" FROM '@BASEPATH@vernacular.txt' WITH DELIMITER AS '	' CSV HEADER;